/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['default']
	const Card: typeof import('./src/components/Card/index')['default']
	const About: typeof import('./src/pages/About/index')['default']
	const Home: typeof import('./src/pages/Home/index')['default']
	const Persons: typeof import('./src/pages/Persons/index')['default']
	const AppDropMenu: typeof import('./src/components/App/DropMenu/index')['default']
	const AppFooter: typeof import('./src/components/App/Footer/index')['default']
	const AppHeader: typeof import('./src/components/App/Header/index')['default']
	const AppLogo: typeof import('./src/components/App/Logo/index')['default']
	const AppThemeToggle: typeof import('./src/components/App/ThemeToggle/index')['default']
	const SectionAboutCard: typeof import('./src/components/Sections/AboutCard/index')['default']
	const SectionContacts: typeof import('./src/components/Sections/Contacts/index')['default']
	const UiMenu: typeof import('./src/components/Ui/Menu/index')['default']
	const UiSearch: typeof import('./src/components/Ui/Search/index')['default']
}