/* generated by unplugin-react-components */
export {}
declare global{
	const About: typeof import('./src/components/about/About')['default']
	const AboutCard: typeof import('./src/components/aboutCard/AboutCard')['default']
	const ButtonClose: typeof import('./src/components/buttonClose/ButtonClose')['default']
	const Card: typeof import('./src/components/card/Card')['default']
	const Cards: typeof import('./src/components/cards/Cards')['default']
	const Contacts: typeof import('./src/components/contacts/Contacts')['default']
	const DropMenu: typeof import('./src/components/dropMenu/DropMenu')['default']
	const Footer: typeof import('./src/components/footer/Footer')['default']
	const Header: typeof import('./src/components/header/Header')['default']
	const Home: typeof import('./src/components/home/Home')['default']
	const Logo: typeof import('./src/components/logo/Logo')['default']
	const Menu: typeof import('./src/components/menu/Menu')['default']
	const persons: typeof import('./src/components/persons/Persons')['default']
	const QuickStart: typeof import('./src/components/quickStart/QuickStart')['default']
	const Search: typeof import('./src/components/search/Search')['default']
	const ThemeToggle: typeof import('./src/components/themeToggle/ThemeToggle')['default']
}