/* generated by unplugin-react-components */
export {}
declare global{
	const ButtonClose: typeof import('./src/components/App/ButtonClose/index')['default']
	const DropMenu: typeof import('./src/components/App/DropMenu/index')['default']
	const Footer: typeof import('./src/components/App/Footer/index')['default']
	const Header: typeof import('./src/components/App/Header/index')['default']
	const Logo: typeof import('./src/components/App/Logo/index')['default']
	const ThemeToggle: typeof import('./src/components/App/ThemeToggle/index')['default']
	const AboutCard: typeof import('./src/components/Cards/AboutCard/index')['default']
	const Card: typeof import('./src/components/Cards/Card/index')['default']
	const About: typeof import('./src/components/Sections/About/index')['default']
	const Contacts: typeof import('./src/components/Sections/Contacts/index')['default']
	const Home: typeof import('./src/components/Sections/Home/index')['default']
	const Menu: typeof import('./src/components/Ui/Menu/index')['default']
	const persons: typeof import('./src/components/Ui/Persons/index')['default']
	const QuickStart: typeof import('./src/components/Ui/QuickStart/index')['default']
	const Search: typeof import('./src/components/Ui/Search/index')['default']
}